name: Scheduled Cross-Exchange Tracker

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create environment file
      run: |
        echo "BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}" > .env
        echo "BINANCE_API_SECRET=${{ secrets.BINANCE_API_SECRET }}" >> .env
        echo "KRAKEN_API_KEY=${{ secrets.KRAKEN_API_KEY }}" >> .env
        echo "KRAKEN_API_SECRET=${{ secrets.KRAKEN_API_SECRET }}" >> .env
      
    - name: Run tracker for 10 minutes
      run: |
        # Run the tracker with a 10-minute timeout
        # Using BTC/USDT with a 2% threshold and 30-second check interval
        timeout 600s python run.py -s BTC -b USDT -t 2.0 -i 30 || code=$?; if [[ $code -eq 124 ]]; then echo "Tracker ran for 10 minutes"; else exit $code; fi
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: arbitrage-logs
        path: arbitrage.log 